tasks:
  - init: rustup target add wasm32-unknown-unknown
  - command: cp /workspace/wasmedge-quickjs/examples/embed_cloudflare/Cargo.toml /workspace/wasmedge-quickjs/Cargo.toml && \
             cargo build --target wasm32-unknown-unknown --release
 